## Data Cleaning and preprossing

In [3]:
import pandas as pd
import numpy as np

### loading dataset

In [4]:
df = pd.read_csv("../data/online_retail_II.csv")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

### data shape

In [5]:
print("Rows and Columns:")
print(df.shape)

Rows and Columns:
(1067371, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

### Missing values

In [7]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

### Duplicate values

In [8]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 34335

In [9]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

### sales column

In [10]:
df["Sales"] = df["Quantity"] * df["Price"]
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Sales
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

### sales statics

In [11]:
df["Sales"].describe()

count    1.067371e+06
mean     1.806987e+01
std      2.924202e+02
min     -1.684696e+05
25%      3.750000e+00
50%      9.900000e+00
75%      1.770000e+01
max      1.684696e+05
Name: Sales, dtype: float64

### conversion of invoice date

In [12]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [13]:
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
Sales                 float64
dtype: object

### Datacleaning

#### removing missing customerIds

In [14]:
print("Rows Before:", df.shape)
df = df.dropna(subset=["Customer ID"])
print("Rows After:", df.shape)

Rows Before: (1067371, 9)
Rows After: (824364, 9)

In [15]:
df = df.dropna(subset=["Description"])
df.shape

(824364, 9)

#### remove duplicate records

In [16]:
print("Before:", df.shape)
df = df.drop_duplicates()
print("After:", df.shape)

Before: (824364, 9)
After: (797885, 9)

#### removing cancelled orders

In [17]:
df = df[~df["Invoice"].astype(str).str.startswith("C")]
df.shape

(779495, 9)

#### removing -ve quantites

In [18]:
df = df[df["Quantity"] > 0]
df.shape

(779495, 9)

#### removing -ve prices

In [19]:
df = df[df["Price"] > 0]
df.shape

(779425, 9)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  object
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
 8   Sales        779425 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 59.5+ MB

In [21]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Sales          0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df["Sales"].describe()

count    779425.000000
mean         22.291823
std         227.427075
min           0.001000
25%           4.950000
50%          12.480000
75%          19.800000
max      168469.600000
Name: Sales, dtype: float64

### data features

In [24]:
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["Day"] = df["InvoiceDate"].dt.day
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Sales,Year,Month,Day
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,1
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,1
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,1

In [26]:
# verifying new columns
df[["InvoiceDate", "Year", "Month", "Day"]].head()

          InvoiceDate  Year  Month  Day
0 2009-12-01 07:45:00  2009     12    1
1 2009-12-01 07:45:00  2009     12    1
2 2009-12-01 07:45:00  2009     12    1
3 2009-12-01 07:45:00  2009     12    1
4 2009-12-01 07:45:00  2009     12    1

### data set overview

In [27]:
print("Final Shape:", df.shape)

Final Shape: (779425, 12)

saving the clean dataset

In [28]:
df.to_csv("../data/cleaned_data.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.